### ISSUE TITLE
Can't simulate virtual sticks

### ISSUE THREAD

**Issue by tdjogi010** [DJI-Mobile-SDK-Tutorials/Android-SimulatorDemo#2]
I am using Mavic Pro. I am unable to simulate movements using virtual stick after starting simulator and enabling virtual stick mode. Auto takeoff and landing works fine in simulator(Z value changes). I am able to control the drone using RC even after enabling virtual stick mode( ideally RC should be disconnected). `isVirtualStickControlModeAvailable` returns true after enabling virtual stick mode. No error is thrown while using `sendVirtualStickFlightControlData` . So why is it not simulating drone movements with the virtual sticks?

Same issue with [Mobile-SDK-Android](https://github.com/dji-sdk/Mobile-SDK-Android)'s virtual stick view. Is there any other thing that needs to be done?Enable some drone or rc mode or something??

Devices:
Mobile : samsung galaxy s7
android os: 7.0
Drone : mavic pro
android studio version: 2.2.3
DJI android sdk : 4.1 and 4.0.2 (both tested)

**Comment by oliverou** [comment]
Hi @tdjogi010 , thanks for your feedbacks. Sorry, I can't get the idea of your question. 

Are you using the SimulatorDemo with DJI Assistant Simulator simultaneously？Have you check the tutorial of this demo: [DJI Simulator Tutorial](http://developer.dji.com/mobile-sdk/documentation/android-tutorials/SimulatorDemo.html) ? You can check the gif animation at the bottom of the tutorial, it's using virtual stick to send simulation data to control the aircraft movement(Yaw, Pitch, Roll) in virtual stick mode. For more details, you can also check this documentation: [Simulator](http://developer.dji.com/mobile-sdk/documentation/introduction/component-guide-flightController.html#simulator). Thanks!

**Comment by tdjogi010** [comment]
@oliverou Yes. I aim to use SimulatorDemo with DJI Assistant Simulator simultaneously. 

But the gif animation at the bottom of the tutorial is not working for me (without the use of  DJI Assistant Simulator i.e only with the use of `Simulator` class/object). But both(DJI Assistant Simulator and `Simulator` object) works fine if I use the drone in the wifi mode, not in rc mode.

**Comment by dji-dev** [comment]
Hi @tdjogi010, you cannot use SimulatorDemo with DJI Assistant Simulator simultaneously, since they both use **Simulator Mode** of the flight controller. Please check this documentation for details: [Aircraft Simulator](http://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-testing.html).

**Comment by tdjogi010** [comment]
@dji-dev I am not using DJI Assistant Simulator and SimulatorDemo simultaneously(i.e. I am not "starting simulation" on both but only individually). The problem I am facing is that simulation doesn't work on rc mode. 

BTW, when I enable virtual sticks, rc sticks still works. Is it not supposed to override rc sticks(or at least in simulation)?

**Comment by oliverou** [comment]
Hi @tdjogi010 , I have tested the SimulatorDemo on Mavic Pro (RC Mode), the simulation works. Please check the following tips and see if you miss something and try again:

1. Connect your Mavic Pro to DJI Go 4 app and check the checklist and see if it's safe to fly. Otherwise, your Mavic Pro may has issues like Low battery, IMU or Compass need calibration, firmware need to update, etc.

2. Once you confirm your Mavic Pro is safe to fly, connect the SimulatorDemo to Mavic Pro, make sure you see the "Mavic Pro connected" on the app's navigation bar, then press **Enable Virtual Stick** button first. Once you see a message say "Enable Virtual Stick Success", press the **Start Simulator** button, you may see a message say "Start Simulator Success" and the text view shows contents. After that, press **Take off** button, the textView will start to update data.

3. Now, either you control the virtual sticks in the app or control the Mavic Pro RC sticks, the simulation will works. You may see the data **Yaw**, **Pitch**, **Roll**, **PosX**, **PosY**, **PosZ** are updating.

For more details, please check the tutorial [DJI Simulator Tutorial](http://developer.dji.com/mobile-sdk/documentation/android-tutorials/SimulatorDemo.html), it explains how to implement the **DJISimulator** feature using DJI Android SDK steps by steps. Thanks!

**Comment by cvance** [comment]
Having this exact issue using Mavic Pro, Android 7.1.2, sdk 4.8.1, RC mode. 

Steps 1 & 2 work fine. However step 3, only the RC sticks update the data. When I move the virtual sticks, nothing. I'm logging calls to sendVirtualStickFlightControlData and I see them complete with no error. However the textview never updates, nor the distance or height numbers on the controller.

**Comment by cvance** [comment]
Also when virtual stick mode is enabled, should the aircraft still respond to RC sticks too? I want to disable the RC sticks and only allow virtual sticks.

**Comment by cvance** [comment]
Appears this bug is only on Mavic 1. When using our Mavic 2, virtual sticks work fine.

**Comment by HosokawaRisako** [comment]
About "Can't simulate virtual sticks # 2"

Please tell me how to automatically land and take off the drone using the virtual stick. I look forward to working with you.
